import * as images from "./images";

export const posts = [
  {
    id: 1,
    category: "food",
    name: "John Smith",
    profilePic: images.image1,
    timePosted: "2 hours ago",
    following: true,
    likeCount: 56,
    commentCount: 23,
    shareCount: 10,
    viewCount: 345,
    content:
      "Check out this delicious pizza I made at home! It's loaded with fresh mozzarella, juicy tomatoes, and aromatic basil on top of a crispy, thin crust. I even added a touch of spicy red pepper flakes for a little extra kick. Trust me, it's the perfect comfort food for any occasion. And the best part? It's so easy to make! Just mix the dough, add the toppings, and bake in the oven. In no time, you'll have a piping hot pizza that's ready to be devoured. So, what are you waiting for? Give it a try and let me know what you think!",
  },
  {
    id: 2,
    category: "travel",
    name: "Sarah Lee",
    profilePic: "images.image2",
    timePosted: "3 days ago",
    following: false,
    likeCount: 102,
    commentCount: 42,
    shareCount: 15,
    viewCount: 789,
    content: "Just got back from an amazing trip to Japan!",
  },
  {
    id: 3,
    category: "fitness",
    name: "Alex Johnson",
    profilePic: images.image3,
    timePosted: "1 hour ago",
    following: true,
    likeCount: 25,
    commentCount: 8,
    shareCount: 2,
    viewCount: 124,
    content: "Just finished a great workout at the gym!",
  },
  {
    id: 4,
    category: "fashion",
    name: "Emily Chen",
    profilePic: images.image4,
    timePosted: "5 hours ago",
    following: false,
    likeCount: 76,
    commentCount: 35,
    shareCount: 5,
    viewCount: 567,
    content: "Loving my new outfit today!",
  },
  {
    id: 5,
    category: "music",
    name: "Mike Williams",
    profilePic: images.image5,
    timePosted: "1 day ago",
    following: true,
    likeCount: 98,
    commentCount: 21,
    shareCount: 7,
    viewCount: 456,
    content: "Had a great time performing at the concert last night!",
  },
  {
    id: 6,
    category: "Fashion",
    name: "Maggie Lee",
    profilePicture: images.image6,
    timePosted: "2 hours ago",
    following: true,
    like: 152,
    comments: 23,
    shares: 10,
    views: 500,
    content:
      "Check out my new outfit! I'm loving this vintage vibe. 😍 #retrofashion #ootd",
  },
  {
    id: 7,
    category: "Food",
    name: "David Johnson",
    profilePicture: images.image7,
    timePosted: "4 hours ago",
    following: false,
    like: 420,
    comments: 56,
    shares: 20,
    views: 800,
    content:
      "I made this amazing pasta dish from scratch tonight. It's so easy and delicious! 😋 #homemadepasta #foodie",
  },
  {
    id: 8,
    category: "Travel",
    name: "Sophia Rodriguez",
    profilePicture: images.image8,
    timePosted: "1 day ago",
    following: true,
    like: 317,
    comments: 41,
    shares: 15,
    views: 1200,
    content:
      "Missing this beautiful view already. Can't wait to go back someday. 🌅 #santorini #travelgram",
  },
  {
    id: 9,
    category: "Fitness",
    name: "Jason Lee",
    profilePicture: images.image9,
    timePosted: "3 days ago",
    following: false,
    like: 238,
    comments: 32,
    shares: 8,
    views: 700,
    content:
      "Just finished an intense workout at the gym. Feeling great! 💪 #fitnessmotivation #workout",
  },
  {
    id: 10,
    category: "Technology",
    name: "Emma Smith",
    profilePicture: images.image10,
    timePosted: "5 days ago",
    following: true,
    like: 101,
    comments: 14,
    shares: 5,
    views: 400,
    content:
      "Got my hands on the new iPhone and it's amazing! The camera is unreal. 📱 #iphone13 #tech",
  },
  {
    id: 11,
    category: "Fashion",
    name: "Kate Doe",
    profilePicture: images.image11,
    timePosted: "2 hours ago",
    following: false,
    likeCount: 289,
    commentCount: 34,
    shareCount: 8,
    viewCount: 1200,
    content: "Just got my new designer dress! 😍 #fashion #designer #ootd",
  },
  {
    id: 12,
    category: "Travel",
    name: "John Smith",
    profilePicture: images.image1,
    timePosted: "1 day ago",
    following: true,
    likeCount: 124,
    commentCount: 12,
    shareCount: 4,
    viewCount: 987,
    content:
      "What a view! Just arrived in Hawaii 🏖️ #travel #hawaii #beachlife",
  },
  {
    id: 13,
    category: "Food",
    name: "Samantha Lee",
    profilePicture: images.image2,
    timePosted: "3 hours ago",
    following: true,
    likeCount: 452,
    commentCount: 56,
    shareCount: 13,
    viewCount: 2500,
    content:
      "I made this delicious cake for my friend's birthday 🎂 #food #baking #yum",
  },
  {
    id: 14,
    category: "Fitness",
    name: "Mark Johnson",
    profilePicture: images.image2,
    timePosted: "5 hours ago",
    following: false,
    likeCount: 63,
    commentCount: 5,
    shareCount: 1,
    viewCount: 890,
    content: "Got in a good workout today 💪 #fitness #gym #workoutmotivation",
  },
  {
    id: 15,
    category: "Music",
    name: "Alicia Keys",
    profilePicture: images.image7,
    timePosted: "4 days ago",
    following: true,
    likeCount: 1589,
    commentCount: 112,
    shareCount: 23,
    viewCount: 8500,
    content:
      "Had an amazing time performing at the Grammys last night! 🎤 #music #grammys #performance",
  },
];
